version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    profiles: [debug, test]
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "8080:80"
  mssql:
    image: "mcr.microsoft.com/mssql/server:latest"
    profiles: [debug]
    container_name: mssql
    hostname: mssql
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
    volumes:
      - vol:/var/opt/mssql
    restart: unless-stopped    
    ports:
      - "1433:1433"
  mssql_test:
    profiles: [test]
    container_name: mssql_test
    hostname: mssql
    build:
       dockerfile: TestDb/Dockerfile
    restart: unless-stopped    
    ports:
      - "1433:1433"
volumes:
  vol:
    external: true
